export const GET_SPENDINGS = 'GET_SPENDINGS';
export const GET_SPENDINGS_SUCCESS = 'GET_SPENDINGS_SUCCESS';
export const GET_SPENDINGS_FAILURE = 'GET_SPENDINGS_FAILURE';

export const SET_NEW_SPENDING = 'SET_NEW_SPENDING';
export const SET_NEW_SPENDING_SUCCESS = 'SET_NEW_SPENDING_SUCCESS';
export const SET_NEW_SPENDING_FAILURE = 'SET_NEW_SPENDING_FAILURE';